apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-rmvq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-rmvq
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-rmvq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-rmvq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-rmvq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vnsz-tenant/nodejs-users/simple-nodejs-app-rmvq@sha256:4276737a9b321595196f218348f91d36cf7000d4c0933961232346e7851eacc5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
